# Reference: https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  # self monitoring
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  # docker monitoring
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080

  # app example
  - job_name: app
    scrape_interval: 1s
    static_configs:
      - targets:
          - app:3333
